## Lecture Notes - Groups and Pivot Tables ##

**Helpful Resource:**
- [Python Reference](http://data8.org/sp22/python-reference.html): Cheat sheet of helpful array & table methods used in Data 8!

**Recommended Readings:**
- [Classifying by One Variable](https://inferentialthinking.com/chapters/08/2/Classifying_by_One_Variable.html)
- [Cross-Classifying by More than One Variable](https://inferentialthinking.com/chapters/08/3/Cross-Classifying_by_More_than_One_Variable.html)

In [89]:
# import modules to be used in this notebook

from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings

In [90]:
# Create a table from scratch with arrays and columns 
#   using Table().with_columns()

names = make_array("apple", "banana", "cranberry", "apple", "cranberry", "apple")
prices = make_array(1.2, 0.29, 3.2, 0.90, 4.2, 1.25)

fruits = Table().with_columns(
        "Name", names,
        "Price", prices
)

fruits

Name      | Price
apple     | 1.2
banana    | 0.29
cranberry | 3.2
apple     | 0.9
cranberry | 4.2
apple     | 1.25

## Groups - `tbl.group()` ##

### Classifying by One Variable ###

Count the number in each category in a table

In [91]:
# return a table view with a count of row of each category

fruits.group("Name")

Name      | count
apple     | 3
banana    | 1
cranberry | 2

In [92]:
# use the optional 2nd argument to average the price of each category

fruits.group("Name", np.average)

Name      | Price average
apple     | 1.11667
banana    | 0.29
cranberry | 3.7

In [93]:
# we learned how to define and use function in Python,
#   so we can define our own function and use it in group
# let's reduce the price by 50%

# return an array of reduced prices of each category

def halfPrice(price):
    """ reduce the price by 50% """
    return price * 0.5

fruits.group("Name", halfPrice)

Name      | Price halfPrice
apple     | [ 0.6    0.45   0.625]
banana    | [ 0.145]
cranberry | [ 1.6  2.1]

In [94]:
# when use tbl.apply() a function to table column,
#.  it returns an array of reduced prices

fruits.apply(halfPrice, "Price")

array([ 0.6  ,  0.145,  1.6  ,  0.45 ,  2.1  ,  0.625])

In [95]:
# create an array of location corresponding to each row
locations = make_array("Santa Rosa", "Petaluma", "Redwood City", "Santa Rosa", "Redwood City", "Palo Alto")

# append the location array to table fruits and assign the table view to fruits_loc
fruits_loc = fruits.with_columns("Location", locations)
fruits_loc

Name      | Price | Location
apple     | 1.2   | Santa Rosa
banana    | 0.29  | Petaluma
cranberry | 3.2   | Redwood City
apple     | 0.9   | Santa Rosa
cranberry | 4.2   | Redwood City
apple     | 1.25  | Palo Alto

In [96]:
# group the table by "Name" column and average the price of each category
fruits_loc.group("Name", np.average)

Name      | Price average | Location average
apple     | 1.11667       |
banana    | 0.29          |
cranberry | 3.7           |

In [97]:
fruits_loc.group("Name", halfPrice)

Name      | Price halfPrice        | Location halfPrice
apple     | [ 0.6    0.45   0.625] |
banana    | [ 0.145]               |
cranberry | [ 1.6  2.1]            |

##### When `tbl.group()` calls a function in the 2nd argument, the function will apply to all columns of the table.  If the function cannot operate on the column, it may display nothing or something weird.

Use `tbl.select()` to select the columns to be displayed

In [98]:
fruits_loc.group("Name", np.average).select("Name", 1)

Name      | Price average
apple     | 1.11667
banana    | 0.29
cranberry | 3.7

In [99]:
fruits_loc.group("Name", np.sum).select("Name", 1)

Name      | Price sum
apple     | 3.35
banana    | 0.29
cranberry | 7.4

## Groups - `tbl.group()` & Pivots - `tbl.pivot()` ##

### Classifying by Two Variables ###

In [100]:
fruits_loc.group("Name")

Name      | count
apple     | 3
banana    | 1
cranberry | 2

In [101]:
fruits_loc.group("Location")

Location     | count
Palo Alto    | 1
Petaluma     | 1
Redwood City | 2
Santa Rosa   | 2

In [102]:
fruits_loc.group(["Name", "Location"])

Name      | Location     | count
apple     | Palo Alto    | 1
apple     | Santa Rosa   | 2
banana    | Petaluma     | 1
cranberry | Redwood City | 2

In [103]:
fruits_loc.group(["Name", "Location"], np.average)

Name      | Location     | Price average
apple     | Palo Alto    | 1.25
apple     | Santa Rosa   | 1.05
banana    | Petaluma     | 0.29
cranberry | Redwood City | 3.7

In [104]:
fruits_loc

Name      | Price | Location
apple     | 1.2   | Santa Rosa
banana    | 0.29  | Petaluma
cranberry | 3.2   | Redwood City
apple     | 0.9   | Santa Rosa
cranberry | 4.2   | Redwood City
apple     | 1.25  | Palo Alto

In [105]:
fruits_loc.pivot("Location", "Name")

Name      | Palo Alto | Petaluma | Redwood City | Santa Rosa
apple     | 1         | 0        | 0            | 2
banana    | 0         | 1        | 0            | 0
cranberry | 0         | 0        | 2            | 0

In [106]:
fruits_loc.pivot("Location", "Name", values="Price", collect=np.average)

Name      | Palo Alto | Petaluma | Redwood City | Santa Rosa
apple     | 1.25      | 0        | 0            | 1.05
banana    | 0         | 0.29     | 0            | 0
cranberry | 0         | 0        | 3.7          | 0

In [107]:
fruits_loc.pivot("Name", "Location", "Price", np.average)

Location     | apple | banana | cranberry
Palo Alto    | 1.25  | 0      | 0
Petaluma     | 0     | 0.29   | 0
Redwood City | 0     | 0      | 3.7
Santa Rosa   | 1.05  | 0      | 0

In [108]:
# example of group and pivot with car data

cars = Table().read_table('Cars2025.csv')
cars.show(10)

In [109]:
# the default behavior of group is counting the length of array after grouping
cars.group('Type')

# we can pass a function to group to apply to the array after grouping
cars.group('Type', np.average)

Type    | Make average | Model average | LowPrice average | HighPrice average | CityMPG average | HwyMPG average | Seating average | Drive average | Acc030 average | Acc060 average | QtrMile average | Braking average | FuelCap average | Length average | Width average | Height average | Wheelbase average | UTurn average | Weight average | Size average
Minivan |              |               | 40.13            | 51.753            | 16.2            | 34.8           | 7.8             |               | 3.24           | 8.14           | 16.36           | 137             | 18.9            | 204            | 79.4          | 69.8           | 121               | 40.4          | 4507.2         |
Pickup  |              |               | 34.7008          | 58.6727           | 13.5385         | 27.2308        | 5.15385         |               | 2.82308        | 7.17692        | 15.5077         | 136.385         | 22.5154         | 217.462        | 77            | 74.5385        | 133.462           | 45.3077       | 4685.38        |
SUV     |              |               | 43.6869          | 65.5996           | 14.9615         | 31             | 6.03846         |               | 3.02308        | 7.66538        | 15.9481         | 132.615         | 18.3731         | 190.577        | 76.7885       | 68.2885        | 112.519           | 39.7115       | 4341.56        |
Sedan   |              |               | 35.6644          | 50.8778           | 20.2            | 42.12          | 5.08            |               | 3.096          | 7.724          | 15.98           | 129.76          | 15.388          | 188.24         | 72.44         | 58.2           | 109.92            | 38.72         | 3540           |
Sporty  |              |               | 48.1475          | 72.3792           | 15.5            | 32.8333        | 3.66667         |               | 2.38333        | 5.43333        | 13.8833         | 123.833         | 16.9333         | 183.167        | 74.5          | 55.5           | 105.833           | 38.6667       | 3651.67        |
Wagon   |              |               | 35.4317          | 48.4167           | 22.3333         | 38             | 5               |               | 3.16667        | 8.23333        | 16.3667         | 129.333         | 15.3333         | 183.667        | 73            | 61.8333        | 108.667           | 38.3333       | 3466.67        |

In [110]:
# we can define the function used by group too
def count(num_array):
    return len(num_array)

# this example was used in Hw4 that shows how group works
def full_array(any_array):
    return any_array

def first_item(any_array):
    return any_array.item(0)

# this behaves like cars.group, but apply to all columns
cars.group('Type', count)

Type    | Make count | Model count | LowPrice count | HighPrice count | CityMPG count | HwyMPG count | Seating count | Drive count | Acc030 count | Acc060 count | QtrMile count | Braking count | FuelCap count | Length count | Width count | Height count | Wheelbase count | UTurn count | Weight count | Size count
Minivan | 5          | 5           | 5              | 5               | 5             | 5            | 5             | 5           | 5            | 5            | 5             | 5             | 5             | 5            | 5           | 5            | 5               | 5           | 5            | 5
Pickup  | 13         | 13          | 13             | 13              | 13            | 13           | 13            | 13          | 13           | 13           | 13            | 13            | 13            | 13           | 13          | 13           | 13              | 13          | 13           | 13
SUV     | 52         | 52          | 52             | 52              | 52            | 52           | 52            | 52          | 52           | 52           | 52            | 52            | 52            | 52           | 52          | 52           | 52              | 52          | 52           | 52
Sedan   | 25         | 25          | 25             | 25              | 25            | 25           | 25            | 25          | 25           | 25           | 25            | 25            | 25            | 25           | 25          | 25           | 25              | 25          | 25           | 25
Sporty  | 6          | 6           | 6              | 6               | 6             | 6            | 6             | 6           | 6            | 6            | 6             | 6             | 6             | 6            | 6           | 6            | 6               | 6           | 6            | 6
Wagon   | 6          | 6           | 6              | 6               | 6             | 6            | 6             | 6           | 6            | 6            | 6             | 6             | 6             | 6            | 6           | 6            | 6               | 6           | 6            | 6

In [111]:
# these two also produce the same output 
cars.pivot('Type','Drive')
cars.pivot('Type', 'Drive', 'LowPrice', collect=count)

Drive | Minivan | Pickup | SUV  | Sedan | Sporty | Wagon
AWD   | 3       | 13     | 52   | 17    | 3      | 2
FWD   | 2       | 0      | 0    | 8     | 0      | 4
RWD   | 0       | 0      | 0    | 0     | 3      | 0

In [112]:
# apply average after pivoting 
cars.pivot('Type','Size','FuelCap',np.average)

Size     | Minivan | Pickup  | SUV     | Sedan   | Sporty | Wagon
Large    | 18.875  | 29.05   | 22.6692 | 21.35   | 0      | 21.7
Midsized | 19      | 20.3286 | 18.7571 | 15.7    | 18.85  | 18.5
Small    | 0       | 17.1    | 14.8222 | 14.2308 | 15.975 | 12.95

In [113]:
# define a function that compute the price range of each model, and use it in pivot
# this is similar to the SF city employee problem in Hw4

# the function needs to operate on an array in order to be passed to group or pivot
def my_range(num_array):
    return max(num_array)-min(num_array)

# this shows the range of Weight after pivoting

cars.pivot('Type','Size','Weight', my_range)

Size     | Minivan | Pickup | SUV  | Sedan | Sporty | Wagon
Large    | 255     | 520    | 1905 | 390   | 0      | 0
Midsized | 0       | 305    | 1565 | 965   | 155    | 0
Small    | 0       | 310    | 1200 | 1360  | 340    | 130